name: btebind
channels:
  - conda-forge
  - anaconda
  - jmcbroome
  - etetoolkit
dependencies:
  - python=3.9
  - numpy
  - seaborn
  - matplotlib
  - pandas
  - scipy
  - bte
  - ete3
  - toytree
  - boost-cpp=1.73.0
  - tbb-devel=2019.0
  - cython
  - protobuf=3.19
