name: btebind
channels:
  - conda-forge
  - anaconda
  - jmcbroome
  - etetoolkit
dependencies:
  - python
  - numpy
  - seaborn
  - matplotlib
  - pandas
  - scipy
  - bte=0.6.0
  - ete3
  - toytree
  - jupyterlab